name: Check Format

on:
  workflow_call:

jobs:
  lint:
    name: Check code format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check the format with ktlint
        run: ./gradlew ktlintCheck