name: Unit Test

on:
  workflow_call:

jobs:
  unit-test:
    name: Run unit test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run unit test
        run: ./gradlew testDebugUnitTest